version: "3.8"
networks:
  backend:
  frontend:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    environment:
      APPLICATION_NAME: whats_app_clone
      BUNDLE_GEMFILE: /app/Gemfile
      PORT: 3000
      JWT_KEY: supersecret
    command: bin/docker-dev-start-web.sh
    networks:
      - backend
      - frontend
    ports:
      - "3000:3000"
volumes:
  bundle:
