default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/whatsapp_clone_development.sqlite3
  cache:
    <<: *default
    database: storage/whatsapp_clone_development_cache.sqlite3
    migrations_path: db/cache_migrate
  cable:
    <<: *default
    database: storage/whatsapp_clone_development_cable.sqlite3
    migrations_path: db/cable_migrate

test:
  <<: *default
  database: storage/whatsapp_clone_test.sqlite3

production:
  <<: *default
  database: storage/whatsapp_clone_production.sqlite3
